name: Go FaaS
version: 0.0.2
description: Go function runtime
license: Apache-2.0
language: go
maintainers:
  - name: lkingland
    email: lkingland2038@gmail.com
    github-id: lkingland
default-template: default
