name: Go Functions
version: 0.0.1
description: Go Functions Runtime
license: Apache-2.0
language: go
maintainers:
  - name: lkingland
    email: lkingland2038@gmail.com
    github-id: lkingland
default-template: http
