FROM golang:alpine
RUN apk add bash

ENV APPSODY_PROJECT_DIR=/project
ENV APPSODY_MOUNTS=.:/project/function
ENV APPSODY_WATCH_DIR=/project/function

ENV APPSODY_TEST="go test ./..."
ENV APPSODY_TEST_ON_CHANGE="$APPSODY_TEST"

ENV APPSODY_RUN="go run ."
ENV APPSODY_RUN_ON_CHANGE="$APPSODY_RUN"

ENV APPSODY_DEBUG="VERBOSE=true go run ."
ENV APPSODY_DEBUG_ON_CHENGE="$APPSODY_DEBUG"

COPY ./LICENSE /licenses/
COPY ./project /project
COPY ./config  /config
COPY ./main.go /project/
COPY ./go.mod  /project/

WORKDIR /project

ENV PORT=8080

EXPOSE 8080
